"""Playground conversation history (routes /api/conversations*).

Extracted from app.py on 28/08. The appearance constants (AVATAR_IDS,
THEME_IDS, LANGS) went to config.py beforehand: they are read by the
settings, by this history AND by the bootstrap, so they did not belong to
the settings section where they lived.

MSG_MAX_CHARS and CONVERSATIONS_MAX are re-imported by app.py, which still
uses them elsewhere.
"""
import html
import json
import re
import secrets
from datetime import datetime

from flask import Blueprint, Response, abort, jsonify, request, session

from auth import login_required
from config import AVATAR_IDS, LANGS, THEME_IDS
from db import get_db

bp = Blueprint('conversations', __name__)

# Stored server-side and no longer in the browser's localStorage: otherwise
# the history is lost when changing machine, browser, or clearing
# the cache. We keep a `client_id` generated by the client so the same
# conversation stays the same row across saves.
# A message can hold a whole file: 20 000 characters cut a 7 000-token file
# (~28 000 characters). We bound loosely per message, and mostly per
# conversation — it is the total that threatens the database, not one message.
MSG_MAX_CHARS  = 400_000
CONV_MAX_CHARS = 2_000_000
# Images attached to a playground message (models that read them). The
# client shrinks them to 1 568 px on the side as JPEG before sending
# (~150-400 Ko): the bound below only stops a client that would not do it.
# Only `data:` URLs pass, never an address: the engine would otherwise go
# fetch it itself on the internal network (SSRF).
IMAGE_DATA_URL = re.compile(r'data:image/(?:png|jpeg|webp|gif);base64,[A-Za-z0-9+/]+={0,2}')
IMAGES_PAR_MESSAGE = 4
IMAGE_MAX_CHARS = 3_000_000


def images_valides(m):
    """A message's images, filtered: image data: URLs, bounded."""
    imgs = m.get('images') if isinstance(m, dict) else None
    if not isinstance(imgs, list):
        return []
    return [u for u in imgs[:IMAGES_PAR_MESSAGE]
            if isinstance(u, str) and len(u) <= IMAGE_MAX_CHARS and IMAGE_DATA_URL.fullmatch(u)]


CONVERSATIONS_MAX = 30           # per user — beyond that, we purge the oldest
# What `GET /api/conversations` agrees to carry. The trim at save time
# (CONV_MAX_CHARS, 2 M per conversation) protects the DATABASE, not the
# network: 30 full conversations make ~60 Mo of JSON, loaded at EVERY
# playground opening. We thus serve the metadata of every conversation, the
# messages of the most recent ones while they fit in the budget, and
# `messages_omis` for the others — which `GET /api/conversations/<id>`
# renders on demand when one is opened.
LISTE_MAX_OCTETS = 8_000_000


def _messages_json(row):
    try:
        messages = json.loads(row['messages'])
    except Exception:
        return None
    return messages if isinstance(messages, list) else None


@bp.route('/api/conversations')
@login_required
def api_conversations():
    rows = get_db().execute(
        "SELECT client_id, title, model, messages, updated_at FROM conversations "
        "WHERE username=? ORDER BY updated_at DESC", (session['username'],))
    out, octets = [], 0
    for r in rows:
        messages = _messages_json(r)
        if messages is None:
            continue
        item = {'id': r['client_id'], 'title': r['title'], 'model': r['model'],
                'ts': r['updated_at']}
        # The FIRST conversation is always served in full, even if it exceeds the
        # budget on its own: a screen opening on an empty thread would be worse
        # than the latency we are trying to avoid.
        if not out or octets + len(r['messages']) <= LISTE_MAX_OCTETS:
            item['messages'] = messages
            octets += len(r['messages'])
        else:
            item['messages'] = []
            item['messages_omis'] = True
        out.append(item)
    return jsonify({'conversations': out})


@bp.route('/api/conversations/<client_id>')
@login_required
def api_conversation(client_id):
    """ONE whole conversation, on demand (see LISTE_MAX_OCTETS)."""
    row = get_db().execute(
        "SELECT client_id, title, model, messages, updated_at FROM conversations "
        "WHERE username=? AND client_id=?",
        (session['username'], client_id)).fetchone()
    if row is None:
        return jsonify({'ok': False, 'error': 'conversation introuvable'}), 404
    messages = _messages_json(row)
    if messages is None:
        return jsonify({'ok': False, 'error': 'conversation illisible'}), 500
    return jsonify({'ok': True, 'conversation': {
        'id': row['client_id'], 'title': row['title'], 'model': row['model'],
        'ts': row['updated_at'], 'messages': messages}})


@bp.route('/conversations', methods=['POST'])
@login_required
def conversations_route():
    username = session['username']
    db = get_db()
    action = request.form.get('action')
    if action == 'save':
        client_id = request.form.get('id', '').strip()[:64]
        title = request.form.get('title', '').strip()[:120] or 'Conversation'
        model = request.form.get('model', '').strip()[:80]
        raw = request.form.get('messages', '[]')
        if not client_id:
            # 400 and not 200: `postFormVerifie` reads the body AND the status, but
            # an `ok:false` in 200 betrays the contract (cf. CLAUDE.md) — a refused
            # save read as a done save.
            return jsonify({'ok': False, 'error': 'id manquant'}), 400
        try:
            messages = json.loads(raw)
            assert isinstance(messages, list)
        except Exception:
            return jsonify({'ok': False, 'error': 'messages invalides'}), 400
        # Size bounds: a conversation must not bloat the database without limit.
        # BUT 20 000 characters per message cut a generated file of barely 7 000
        # tokens (~28 000 characters): back in the history, the file was truncated
        # while it was complete on screen. So we bound loosely per message, then
        # bound the TOTAL by dropping the oldest messages — which always
        # preserves the last produced
        # file.
        # `hidden` is kept: without it, an answer to questions turns back into an
        # ordinary message on reload and shifts the whole rendering.
        messages = [{'role': m.get('role'),
                     'content': str(m.get('content', ''))[:MSG_MAX_CHARS],
                     **({'hidden': True} if m.get('hidden') else {}),
                     # Kept: without them, an answer cut by the network
                     # looked finished again after a reload, and the cause
                     # could no longer be diagnosed after the fact.
                     **({'isError': True} if m.get('isError') else {}),
                     **({'truncated': True} if m.get('truncated') else {}),
                     # Attached images: without them, a reloaded conversation
                     # lost what the model had seen. Counted in
                     # CONV_MAX_CHARS like the rest: a too heavy conversation
                     # loses its oldest messages, images included.
                     **({'images': imgs} if (imgs := images_valides(m)) and m.get('role') == 'user' else {})}
                    for m in messages if m.get('role') in ('user', 'assistant')][-60:]
        # INCREMENTAL trim: re-serializing 2 Mo at every removed message cost up
        # to 60 serializations per save, in the gunicorn thread. We measure once,
        # then decrement by the size of the removed message.
        total = len(json.dumps(messages, ensure_ascii=False))
        while total > CONV_MAX_CHARS and len(messages) > 1:
            retire = messages.pop(0)
            total -= len(json.dumps(retire, ensure_ascii=False)) + 2
        # Safety net: if the approximation was wrong, we finish with the exact
        # measurement. It only runs on a mismatch, never in the common case.
        while len(json.dumps(messages, ensure_ascii=False)) > CONV_MAX_CHARS and len(messages) > 1:
            messages.pop(0)
        db.execute(
            "INSERT INTO conversations (username, client_id, title, model, messages, updated_at) "
            "VALUES (?,?,?,?,?,?) ON CONFLICT(username, client_id) DO UPDATE SET "
            "title=excluded.title, model=excluded.model, messages=excluded.messages, "
            "updated_at=excluded.updated_at",
            (username, client_id, title, model, json.dumps(messages, ensure_ascii=False),
             datetime.now().isoformat()))
        db.execute(
            "DELETE FROM conversations WHERE username=? AND client_id NOT IN ("
            "  SELECT client_id FROM conversations WHERE username=? "
            "  ORDER BY updated_at DESC LIMIT ?)",
            (username, username, CONVERSATIONS_MAX))
        db.commit()
        return jsonify({'ok': True})
    if action == 'delete':
        cur = db.execute("DELETE FROM conversations WHERE username=? AND client_id=?",
                         (username, request.form.get('id', '')))
        db.commit()
        # `deleted` = the number of ITS deleted rows. An unknown identifier
        # — including one from ANOTHER account — counts 0: the answer thus does
        # not say which of the two cases it is (no existence oracle), but it no
        # longer claims to have deleted anything. We no longer answer 204:
        # `postFormVerifie` reads a 204 as a success, so a deletion that had
        # deleted nothing displayed as done (found by
        # tests/test_autorisation_croisee.py).
        return jsonify({'ok': True, 'deleted': cur.rowcount})
    return jsonify({'ok': False, 'error': f"Action inconnue : {action!r}"}), 400


@bp.route('/conversations/share', methods=['POST'])
@login_required
def conversations_share():
    """Creates a read-only sharing link for a conversation. We duplicate the
    snapshot into conversation_shares: the share reveals only what was shared
    and survives the deletion of the original."""
    # The playground sends JSON (sendJSON); we accept the form too.
    data = request.get_json(silent=True) or request.form
    client_id = str(data.get('client_id', '')).strip()[:64]
    if not client_id:
        return jsonify({'ok': False, 'error': 'id manquant'}), 400
    db = get_db()
    row = db.execute(
        "SELECT title, model, messages FROM conversations WHERE username=? AND client_id=?",
        (session['username'], client_id)).fetchone()
    if not row:
        return jsonify({'ok': False, 'error': 'conversation introuvable'}), 404
    token = secrets.token_urlsafe(24)
    db.execute(
        "INSERT INTO conversation_shares (token, username, title, model, messages, created_at) "
        "VALUES (?,?,?,?,?,?)",
        (token, session['username'], row['title'], row['model'], row['messages'],
         datetime.now().isoformat()))
    db.commit()
    return jsonify({'ok': True, 'token': token})


@bp.route('/c/<token>')
@login_required
def share_view(token):
    """Read-only view of a shared conversation, RESERVED TO LOGGED-IN USERS:
    a leaked link (forum, screenshot) shows nothing to an anonymous visitor,
    it is sent back to the login page. The token stays opaque and de facto
    single-use (we never list the links)."""
    db = get_db()
    row = db.execute(
        "SELECT title, model, messages, views FROM conversation_shares WHERE token=?",
        (token,)).fetchone()
    if not row:
        abort(404)
    try:
        messages = json.loads(row['messages'])
    except Exception:
        messages = []
    db.execute("UPDATE conversation_shares SET views=views+1 WHERE token=?", (token,))
    db.commit()
    title = html.escape(row['title'])
    model = html.escape(row['model'])
    blocks = []
    for m in messages:
        role = m.get('role')
        if role not in ('user', 'assistant'):
            continue
        # HIDDEN messages do not leave the share: they are the answers
        # to the question cards and the internal resume instructions
        # (```edit, « continue », editing protocol). The playground's
        # Markdown export already skips them; the share page showed
        # them — so the recipient of a link saw prompts the author
        # does not even see in their own thread.
        if m.get('hidden'):
            continue
        content = html.escape(m.get('content', '')).replace('\n', '<br>')
        who = "Vous" if role == 'user' else "Assistant"
        color = "#1d4ed8" if role == 'user' else "#059669"
        blocks.append(f'<div style="margin:0 0 18px">'
                      f'<div style="font:600 13px system-ui;color:{color};margin-bottom:6px">{who}</div>'
                      f'<div style="font:400 15px/1.6 system-ui;color:#111827;white-space:pre-wrap">{content}</div>'
                      f'</div>')
    body = "\n".join(blocks)
    html_doc = f"""<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title></head>
<body style="margin:0;background:#f9fafb;color:#111827;font:15px/1.6 system-ui">
<div style="max-width:760px;margin:0 auto;padding:32px 20px">
<h1 style="font:700 22px system-ui;margin:0 0 4px">{title}</h1>
<p style="margin:0 0 24px;color:#6b7280;font:13px system-ui">Modèle : {model or "—"}</p>
{body}
<p style="margin-top:32px;color:#9ca3af;font:12px system-ui">Partagé depuis Cronos</p>
</div></body></html>"""
    return Response(html_doc, mimetype='text/html')


@bp.route('/settings/appearance', methods=['POST'])
@login_required
def settings_appearance():
    """Theme and language. Each value is validated against its allowlist:
    they end up in a theme selector and a translation catalog,
    no question of accepting free text.
    """
    theme_id = request.form.get('theme_id')
    lang = request.form.get('lang')
    db = get_db()
    if theme_id is not None:
        if theme_id not in THEME_IDS:
            # 400 and not 200: a refusal sent with the success status forces
            # every caller to remember reading the body — this one did not.
            return jsonify({'ok': False, 'error': 'Thème inconnu.'}), 400
        db.execute("INSERT INTO user_prefs (username, theme_id) VALUES (?,?) "
                   "ON CONFLICT(username) DO UPDATE SET theme_id=excluded.theme_id",
                   (session['username'], theme_id))
    if lang is not None:
        if lang not in LANGS:
            return jsonify({'ok': False, 'error': 'Langue inconnue.'}), 400
        db.execute("INSERT INTO user_prefs (username, lang) VALUES (?,?) "
                   "ON CONFLICT(username) DO UPDATE SET lang=excluded.lang",
                   (session['username'], lang))
    db.commit()
    return jsonify({'ok': True})


@bp.route('/settings/avatar', methods=['POST'])
@login_required
def settings_avatar():
    avatar_id = request.form.get('avatar_id', '')
    if not avatar_id or avatar_id == 'genere':
        # GENERATED AVATAR: the image is built from the handle (blobatar,
        # see lib/user-avatar.tsx), so there is nothing to store — `NULL` is
        # the « no logo » choice, and it is every account's DEFAULT.
        avatar_id = None
    elif avatar_id not in AVATAR_IDS:
        # `flash` is rendered by NO template (the UI is Next.js): a refused
        # avatar left the screen showing the new choice until reload, without
        # a word. We answer what the caller can read.
        return jsonify({'ok': False, 'error': 'Avatar inconnu.'}), 400
    db = get_db()
    db.execute(
        "INSERT INTO user_prefs (username, avatar_id) VALUES (?,?) "
        "ON CONFLICT(username) DO UPDATE SET avatar_id=excluded.avatar_id",
        (session['username'], avatar_id))
    db.commit()
    return jsonify({'ok': True})
