"""Historique des conversations du playground (routes /api/conversations*).

Extrait de app.py le 28/08. Les constantes d'apparence (AVATAR_IDS, THEME_IDS,
LANGS) sont parties dans config.py au prealable : elles sont lues par les
reglages, par cet historique ET par l'amorcage, donc elles n'appartenaient pas
a la section des reglages ou elles vivaient.

MSG_MAX_CHARS et CONVERSATIONS_MAX sont reimportes par app.py, qui les utilise
encore ailleurs.
"""
import json
from datetime import datetime

from flask import Blueprint, flash, jsonify, request, session

from auth import login_required
from config import AVATAR_IDS, LANGS, THEME_IDS
from db import get_db

bp = Blueprint('conversations', __name__)

# Stored server-side and no longer in the browser's localStorage: otherwise
# the history is lost when changing machine, browser, or clearing
# the cache. We keep a `client_id` generated by the client so the same
# conversation stays the same row across saves.
# Un message peut contenir un fichier entier : 20 000 caractères coupaient un
# fichier de 7 000 tokens (~28 000 caractères). On borne large par message, et
# surtout par conversation — c'est le total qui menace la base, pas un message.
MSG_MAX_CHARS  = 400_000
CONV_MAX_CHARS = 2_000_000
CONVERSATIONS_MAX = 30           # per user — beyond that, we purge the oldest


@bp.route('/api/conversations')
@login_required
def api_conversations():
    rows = get_db().execute(
        "SELECT client_id, title, model, messages, updated_at FROM conversations "
        "WHERE username=? ORDER BY updated_at DESC", (session['username'],))
    out = []
    for r in rows:
        try:
            messages = json.loads(r['messages'])
        except Exception:
            continue
        out.append({'id': r['client_id'], 'title': r['title'], 'model': r['model'],
                    'ts': r['updated_at'], 'messages': messages})
    return jsonify({'conversations': out})


@bp.route('/conversations', methods=['POST'])
@login_required
def conversations_route():
    username = session['username']
    db = get_db()
    action = request.form.get('action')
    if action == 'save':
        client_id = request.form.get('id', '').strip()[:64]
        title = request.form.get('title', '').strip()[:120] or 'Conversation'
        model = request.form.get('model', '').strip()[:80]
        raw = request.form.get('messages', '[]')
        if not client_id:
            return jsonify({'ok': False, 'error': 'id manquant'})
        try:
            messages = json.loads(raw)
            assert isinstance(messages, list)
        except Exception:
            return jsonify({'ok': False, 'error': 'messages invalides'})
        # Bornes de taille : une conversation ne doit pas gonfler la base sans
        # limite. MAIS 20 000 caractères par message coupaient un fichier généré
        # d'à peine 7 000 tokens (~28 000 caractères) : au retour dans
        # l'historique, le fichier était tronqué alors qu'il était complet à
        # l'écran. On borne donc large par message, puis on borne le TOTAL en
        # retirant les plus anciens messages — ce qui préserve toujours le
        # dernier fichier produit.
        # `hidden` est conservé : sans lui, une réponse à des questions redevient
        # un message ordinaire au rechargement et décale tout le rendu.
        messages = [{'role': m.get('role'),
                     'content': str(m.get('content', ''))[:MSG_MAX_CHARS],
                     **({'hidden': True} if m.get('hidden') else {}),
                     # Conservés : sans eux, une réponse coupée par le réseau
                     # repassait pour finie après un rechargement, et on ne
                     # pouvait plus diagnostiquer la cause a posteriori.
                     **({'isError': True} if m.get('isError') else {}),
                     **({'truncated': True} if m.get('truncated') else {})}
                    for m in messages if m.get('role') in ('user', 'assistant')][-60:]
        while len(json.dumps(messages)) > CONV_MAX_CHARS and len(messages) > 1:
            messages.pop(0)
        db.execute(
            "INSERT INTO conversations (username, client_id, title, model, messages, updated_at) "
            "VALUES (?,?,?,?,?,?) ON CONFLICT(username, client_id) DO UPDATE SET "
            "title=excluded.title, model=excluded.model, messages=excluded.messages, "
            "updated_at=excluded.updated_at",
            (username, client_id, title, model, json.dumps(messages, ensure_ascii=False),
             datetime.now().isoformat()))
        db.execute(
            "DELETE FROM conversations WHERE username=? AND client_id NOT IN ("
            "  SELECT client_id FROM conversations WHERE username=? "
            "  ORDER BY updated_at DESC LIMIT ?)",
            (username, username, CONVERSATIONS_MAX))
        db.commit()
        return jsonify({'ok': True})
    if action == 'delete':
        db.execute("DELETE FROM conversations WHERE username=? AND client_id=?",
                   (username, request.form.get('id', '')))
        db.commit()
    return ('', 204)


@bp.route('/settings/appearance', methods=['POST'])
@login_required
def settings_appearance():
    """Theme and language. Each value is validated against its allowlist:
    they end up in a theme selector and a translation catalog,
    no question of accepting free text.
    """
    theme_id = request.form.get('theme_id')
    lang = request.form.get('lang')
    db = get_db()
    if theme_id is not None:
        if theme_id not in THEME_IDS:
            return jsonify({'ok': False, 'error': 'Thème inconnu.'})
        db.execute("INSERT INTO user_prefs (username, theme_id) VALUES (?,?) "
                   "ON CONFLICT(username) DO UPDATE SET theme_id=excluded.theme_id",
                   (session['username'], theme_id))
    if lang is not None:
        if lang not in LANGS:
            return jsonify({'ok': False, 'error': 'Langue inconnue.'})
        db.execute("INSERT INTO user_prefs (username, lang) VALUES (?,?) "
                   "ON CONFLICT(username) DO UPDATE SET lang=excluded.lang",
                   (session['username'], lang))
    db.commit()
    return jsonify({'ok': True})


@bp.route('/settings/avatar', methods=['POST'])
@login_required
def settings_avatar():
    avatar_id = request.form.get('avatar_id', '')
    if avatar_id not in AVATAR_IDS:
        flash("Avatar invalide.", "danger")
        return ('', 204)
    db = get_db()
    db.execute(
        "INSERT INTO user_prefs (username, avatar_id) VALUES (?,?) "
        "ON CONFLICT(username) DO UPDATE SET avatar_id=excluded.avatar_id",
        (session['username'], avatar_id))
    db.commit()
    return ('', 204)
