"""Preview of an HTML page generated by the model, in a sandbox.

Extracted from app.py on 28/08. The monolith's « Apercu » banner also covered
the playground chat, admin routes, search and the ranking: only the preview
is here. The rest awaits its own split.

The pages are kept in SQLite: ephemeral keys, tied to an ongoing
conversation, purged after an hour (and capped in count). The database
rather than an in-memory dict because gunicorn serves several workers: a
preview created in one worker must be readable by the next GET, which may hit another.
"""
import secrets
import time

from flask import Blueprint, Response, abort, jsonify, request, session

from auth import login_required
from conversation_routes import MSG_MAX_CHARS
from db import get_db

bp = Blueprint('preview', __name__)

_PREVIEW_TTL = 3600             # 1 h: time to look at it, not to store it
_PREVIEW_MAX = 40               # PER-ACCOUNT cap (see _preview_purge)
_PREVIEW_MAX_TOTAL = 400        # bound on the whole table (one page = up to 400 ko)


def _preview_purge(username):
    """Purges expired previews and caps them, PER ACCOUNT then globally.

    The cap used to be global: the 200 most recent previews, all accounts
    mixed. An account chaining generations — exactly what a working session
    on the playground does — therefore evicted the OTHERS' previews, whose
    iframe started answering 404 (« preview not found ») in the middle of a
    conversation. The per-account cap can now only evict its own previews;
    the global cap remains a size bound for the database (one page can weigh
    400 ko).

    Runs at every creation; SQLite does the purge and the caps in the same
    transaction, so there is no race between gunicorn workers."""
    db = get_db()
    db.execute("DELETE FROM previews WHERE created_at < ?", (time.time() - _PREVIEW_TTL,))
    db.execute("""DELETE FROM previews WHERE username=? AND id NOT IN (
                     SELECT id FROM previews WHERE username=?
                     ORDER BY created_at DESC LIMIT ?)""",
               (username, username, _PREVIEW_MAX))
    db.execute("""DELETE FROM previews WHERE id NOT IN (
                     SELECT id FROM previews ORDER BY created_at DESC LIMIT ?)""",
               (_PREVIEW_MAX_TOTAL,))
    db.commit()


@bp.route('/playground/preview', methods=['POST'])
@login_required
def playground_preview_create():
    data = request.get_json(silent=True) or {}
    html = str(data.get('html', ''))[:MSG_MAX_CHARS]
    if not html.strip():
        return jsonify({'ok': False, 'error': 'vide'}), 400
    _preview_purge(session['username'])
    pid = secrets.token_urlsafe(18)
    db = get_db()
    db.execute("INSERT INTO previews (id, username, html, created_at) VALUES (?,?,?,?)",
               (pid, session['username'], html, time.time()))
    db.commit()
    return jsonify({'ok': True, 'id': pid})


# A generated page can be syntactically perfect and do nothing: wrong library
# version, nonexistent method, undefined variable. No static analysis sees
# this — only execution reveals it. The preview already runs the page: we
# graft onto it a way to REPORT its errors back to the playground, which can
# then display them and propose a fix. The script is inserted first to catch
# also what breaks at load time.
_PREVIEW_RAPPORT = """<script>
(function(){
  var envoye = 0;
  // Le bac à sable lui-même provoque des erreurs qui ne disent RIEN sur la page :
  // origine opaque (donc parent.document illisible, localStorage interdit), et
  // ressources externes bloquées. Les remonter accusait à tort du code correct.
  var bruit = /cross-origin|Blocked a frame|SecurityError|operation is insecure|localStorage|sessionStorage|indexedDB|Access is denied/i;
  function dire(m){
    var s = String(m);
    if (bruit.test(s)) return;
    if (envoye++ > 3) return;                       // on ne noie pas le parent
    try { parent.postMessage({ cronosPreviewError: s.slice(0, 400) }, '*'); } catch (e) {}
  }
  window.addEventListener('error', function(e){
    dire(e && e.message ? e.message : 'erreur de chargement');
  }, true);
  window.addEventListener('unhandledrejection', function(e){
    dire((e && e.reason && e.reason.message) || 'promesse rejetee');
  });
})();
</script>"""


def _preview_avec_rapport(html):
    """Inserts the error spy as early as possible in the document."""
    for balise in ('<head>', '<HEAD>', '<html>', '<HTML>'):
        i = html.find(balise)
        if i >= 0:
            return html[:i + len(balise)] + _PREVIEW_RAPPORT + html[i + len(balise):]
    return _PREVIEW_RAPPORT + html


@bp.route('/playground/preview/<pid>')
@login_required
def playground_preview_show(pid):
    row = get_db().execute(
        "SELECT username, html FROM previews WHERE id=? AND username=?",
        (pid, session['username'])).fetchone()
    # Per-account isolation: another user's preview is not readable.
    if not row:
        abort(404)
    resp = Response(_preview_avec_rapport(row['html']), mimetype='text/html')
    # `sandbox` in the header → opaque origin, even outside an iframe. The other
    # directives are deliberately absent: the page must be able to run.
    # `default-src 'none'` is the missing piece: without it a generated page
    # made the VIEWER's browser fetch scripts/images from any host — a blind
    # browser-side SSRF and a tracking vector (audit 2026-10-06, L1). The page
    # keeps its own inline script and styles, and its own images (data:/blob:).
    resp.headers['Content-Security-Policy'] = (
        'sandbox allow-scripts allow-forms allow-modals allow-popups; '
        "default-src 'none'; script-src 'unsafe-inline'; "
        "img-src 'self' data: blob:; style-src 'unsafe-inline'; "
        "connect-src 'self'; font-src 'self' data:")
    resp.headers['X-Content-Type-Options'] = 'nosniff'
    resp.headers['Cache-Control'] = 'no-store'
    return resp
