# -*- coding: utf-8 -*-
"""Couverture des routes du portail — le registre des décisions.

Chaque endpoint Flask doit être soit COUVERT par un parcours e2e, soit EXCLU
avec une motivation écrite (« exclu » + la raison). Un route ajoutée plus tard
n'est pas dans ce registre : `verifier_couverture.py` échoue alors avec « route
non couverte — décide : ajoute-la à un parcours ou motive son exclusion ».
C'est le même contrat que `GardeDesRoutesTest` pour les routes publiques :
la question n'est pas « comment faire passer le test » mais « qui a décidé
que cette route n'avait pas besoin d'être testée ».

Format : ROUTES[endpoint] = ("parcours", "<parcours qui la touche>")
                          | ("exclu",   "<motivation en français>")
Généré à partir de l'inventaire réel (`tests/e2e/dump_routes.py`) — un rechargé
de l'inventaire qui ne correspond plus à ce registre fait rougir le contrôle.
"""

ROUTES = {
    'admin.add_model_cfg': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.add_ocr_cfg': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.add_voice_cfg': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.admin_announce': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.admin_audit': ('parcours', 'j09_admin'),
    'admin.admin_branding': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.admin_consumption': ('exclu', 'lecture admin secondaire : hors des onglets vérifiés par j09_admin'),
    'admin.admin_email_config': ('exclu', 'lecture admin secondaire : hors des onglets vérifiés par j09_admin'),
    'admin.admin_email_test': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.admin_groups_create': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.admin_groups_delete': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.admin_platform': ('parcours', 'j09_admin'),
    'admin.admin_revoke_sessions': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.admin_runner_logs': ('exclu', 'lecture admin secondaire : hors des onglets vérifiés par j09_admin'),
    'admin.admin_runner_stream': ('parcours', 'j09_admin'),
    'admin.admin_sidecar_logs': ('exclu', 'lecture admin secondaire : hors des onglets vérifiés par j09_admin'),
    'admin.admin_support_feedback': ('exclu', 'lecture admin secondaire : hors des onglets vérifiés par j09_admin'),
    'admin.admin_user_block': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.admin_user_detail': ('exclu', 'lecture admin secondaire : hors des onglets vérifiés par j09_admin'),
    'admin.admin_user_purge': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.admin_user_unblock': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.admin_users_create': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.admin_users_delete': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.admin_users_update': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.admin_valider': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.admin_valider_etat': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.api_admin': ('parcours', 'j09_admin'),
    'admin.api_admin_users': ('parcours', 'j09_admin (onglet Utilisateurs)'),
    'admin.api_announcements': ('exclu', 'annonces : lue seulement quand une annonce est active (aucune pendant la validation)'),
    'admin.api_announcements_seen': ('exclu', 'annonces : marquage « vue » — écriture de préférence'),
    'admin.approve_budget': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.delete_model_cfg': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.delete_ocr_cfg': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.delete_voice_cfg': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.edit_model_cfg': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.internal_authcheck': ('parcours', "j13_securite (injoignable de l'extérieur)"),
    'admin.launch_image': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.launch_model': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.launch_music': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.launch_ocr_cfg': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.launch_voice_cfg': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.reject_budget': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.set_user_budget': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.start_asr': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.start_image': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.start_music': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.start_ocr': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.start_video': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.start_voice': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.stop_asr': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.stop_image': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.stop_model': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.stop_music': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.stop_ocr': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.stop_video': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.stop_voice': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.system_stats': ('exclu', 'lecture admin secondaire : hors des onglets vérifiés par j09_admin'),
    'admin.toggle_maintenance': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.update_request': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.update_settings': ('exclu', 'action admin à effet réel : jamais déclenchée par un parcours (la validation doit rester sûre en production — aucun lancement, aucune écriture)'),
    'admin.usage_hourly': ('exclu', 'lecture admin secondaire : hors des onglets vérifiés par j09_admin'),
    'api_branding_logo': ('exclu', 'logo personnalisé absent du déploiement (favicon par défaut) : route sans objet ici'),
    'api_config': ('parcours', 'j01_connexion'),
    'api_csrf': ('parcours', 'j01_connexion (et j10_cles_api)'),
    'api_health': ('exclu', 'agrégat de santé : non appelé par la coquille actuelle (vérifié par capture réseau)'),
    'api_home': ('parcours', 'j11_balayage_pages (accueil)'),
    'api_keys': ('parcours', 'j10_cles_api (liste des clés)'),
    'api_model_request': ('exclu', 'bouton « Demander un modèle » (média) : envoie un email réel + anti-spam 30 min — non déclenché pour ne pas polluer la file admin'),
    'api_modelhealth': ('parcours', 'j11_balayage_pages (accueil)'),
    'api_notifications': ('parcours', 'j11_balayage_pages (coquille)'),
    'api_notifications_seen': ('exclu', 'marquage des notifications comme vues : écriture de préférence'),
    'api_onboarding_done': ('exclu', 'onboarding déjà soldé pour le compte de démo'),
    'api_pending_count': ('parcours', 'j11_balayage_pages (coquille)'),
    'api_ranking': ('parcours', 'j12_actions_pages (classement)'),
    'api_search': ('parcours', 'j12_actions_pages (recherche HF)'),
    'api_whoami': ('parcours', 'j01_connexion (coquille)'),
    'asr.api_transcribe': ('exclu', 'dictée vocale : nécessite un micro (matériel)'),
    'asr.api_transcribe_available': ('parcours', 'j02_chat (bouton dictée)'),
    'chat.api_playground_data': ('parcours', 'j02_chat'),
    'chat.playground_chat': ('parcours', 'j02_chat, j03_reflexion, j04_outil_image, j05_recherche_web, j07_conversations, j08_export'),
    'chat.playground_summarize': ('exclu', 'bouton « Résumer » : consomme le modèle pour un cosmétique'),
    'chat.playground_title': ('exclu', 'bouton « Titrer automatiquement » : consomme le modèle pour un cosmétique'),
    'chat.support_chat': ('parcours', 'j12_actions_pages'),
    'chat.support_confirm': ('exclu', 'action sensible (révocation/lancement) : jamais confirmée par un parcours'),
    'chat.support_feedback': ('exclu', 'vote de qualité : laisserait de fausses données dans le suivi'),
    'chat.support_thread_clear': ('exclu', 'effacement du fil Support : destructif'),
    'chat.support_thread_get': ('parcours', 'j12_actions_pages (fil Support)'),
    'conversations.api_conversation': ('parcours', 'j07_conversations (ouverture/renommage)'),
    'conversations.api_conversations': ('parcours', 'j07_conversations (historique)'),
    'conversations.conversations_route': ('parcours', 'j07_conversations (sauvegarde du fil)'),
    'conversations.conversations_share': ('exclu', "création d'un lien public : publierait une conversation du compte de test"),
    'conversations.settings_appearance': ('exclu', 'apparence : préférence visuelle, sans enjeu de validation'),
    'conversations.settings_avatar': ('exclu', 'avatar : préférence visuelle, sans enjeu de validation'),
    'conversations.share_view': ('exclu', "vue publique d'un partage : nécessite un jeton créé par la route précédente"),
    'discord.api_discord_status': ('exclu', "liaison Discord : OAuth externe sur le compte de l'opérateur"),
    'discord.discord_callback': ('exclu', "liaison Discord : OAuth externe sur le compte de l'opérateur"),
    'discord.discord_link': ('exclu', "liaison Discord : OAuth externe sur le compte de l'opérateur"),
    'discord.discord_unlink': ('exclu', "liaison Discord : délier un compte réel de l'opérateur"),
    'docs': ('exclu', 'page de documentation OpenAPI : lecture, sans geste utilisateur'),
    'healthz': ('exclu', "sonde de vivacité pour l'infrastructure (healthcheck/monitoring), pas un parcours"),
    'image.api_image_cancel': ('exclu', "annulation d'une génération : geste destructif, jamais automatisé"),
    'image.api_image_delete': ('exclu', "suppression d'une image : geste destructif, jamais automatisé"),
    'image.api_image_generate': ('exclu', 'génération lourde depuis la page Image : non déclenchée (charge) — le chemin outil du playground est couvert par j04_outil_image'),
    'image.api_image_history': ('parcours', 'j12_actions_pages (page /image)'),
    'image.api_image_status': ('exclu', "suivi d'une génération : rien à suivre sans génération (le chemin outil est couvert par j04_outil_image)"),
    'image.image_file': ('parcours', 'j04_outil_image (image servie dans la conversation)'),
    'index': ('parcours', 'j01_connexion, j11_balayage_pages'),
    'keys': ('parcours', 'j10_cles_api (création/révocation)'),
    'latence.api_latence': ('parcours', 'j11_balayage_pages (coquille)'),
    'login': ('parcours', 'j01_connexion'),
    'login_sso': ('parcours', 'j01_connexion (redirection OIDC)'),
    'logout': ('parcours', 'j01_connexion'),
    'memory.api_memory': ('parcours', 'j12_actions_pages (lecture)'),
    'memory.api_memory_add': ('exclu', "ajout d'un fait en mémoire : écriture de données du compte"),
    'memory.api_memory_enabled': ('parcours', 'j12_actions_pages (écriture + retour arrière)'),
    'memory.api_memory_export': ('exclu', 'export de la mémoire : lecture lourde, sans enjeu de validation'),
    'memory.api_memory_export_md': ('exclu', 'export de la mémoire : lecture lourde, sans enjeu de validation'),
    'memory.api_memory_forget': ('exclu', "oubli d'un fait : destruction de données"),
    'memory.api_memory_import': ('exclu', 'import en mémoire : écriture de données du compte'),
    'memory.api_memory_import_md': ('exclu', 'import en mémoire : écriture de données du compte'),
    'memory.api_memory_purge': ('exclu', 'purge de la mémoire : destruction de données'),
    'memory.api_memory_update': ('exclu', "édition d'un fait : écriture de données du compte"),
    'music.api_music_cancel': ('exclu', "annulation d'une composition : geste destructif, jamais automatisé"),
    'music.api_music_generate': ('exclu', 'génération musicale lourde (plusieurs minutes) : hors budget de la validation'),
    'music.api_music_history': ('parcours', 'j12_actions_pages (page /music)'),
    'music.api_music_status': ('exclu', "suivi d'une génération : rien à suivre sans génération"),
    'music.music_file': ('exclu', 'fichier produit servi : rien à servir sans génération'),
    'oauth_callback': ('exclu', 'retour OIDC du fournisseur : traverser Authentik est impossible en automatisé (2FA/LDAP)'),
    'ocr.api_ocr_extract': ('exclu', 'extraction OCR (upload) : service à la demande, non déclenchée (charge)'),
    'ocr.api_ocr_history': ('parcours', 'j12_actions_pages (page /ocr)'),
    'ocr.ocr_image': ('exclu', 'image du résultat OCR : rien à servir sans extraction'),
    'preview.playground_preview_create': ('exclu', 'aperçu HTML généré par le playground : non utilisé par les parcours'),
    'preview.playground_preview_show': ('exclu', 'aperçu HTML généré par le playground : non utilisé par les parcours'),
    'prom_metrics': ('parcours', 'j13_securite (refus public vérifié)'),
    'request_model': ('parcours', 'j12_actions_pages (formulaire /request)'),
    'settings.api_account_delete': ('exclu', 'suppression de compte : destructif'),
    'settings.api_account_password': ('exclu', 'changement de mot de passe : modifierait le compte de démo'),
    'settings.api_account_sessions': ('exclu', 'liste des sessions : lecture liée à la révocation, non nécessaire'),
    'settings.api_account_sessions_revoke': ('exclu', 'révocation de session : couperait la session du compte de test'),
    'settings.api_settings': ('parcours', 'j10_cles_api (dialogue Réglages)'),
    'settings.mcp_servers_route': ('exclu', "ajout/suppression de serveurs MCP : configuration de l'opérateur"),
    'settings.skills_route': ('exclu', 'compétences personnelles : écriture de préférences'),
    'static': ('parcours', 'j11_balayage_pages (coquille)'),
    'video.api_video_cancel': ('exclu', "annulation d'une génération : geste destructif, jamais automatisé"),
    'video.api_video_generate': ('exclu', 'génération vidéo lourde (5-10 min) : hors budget de la validation'),
    'video.api_video_history': ('parcours', 'j12_actions_pages (page /video)'),
    'video.api_video_status': ('exclu', "suivi d'une génération : rien à suivre sans génération"),
    'video.video_file': ('exclu', 'fichier produit servi : rien à servir sans génération'),
    'voice.api_voice_generate': ('exclu', 'clonage vocal lourd : hors budget de la validation'),
    'voice.api_voice_history': ('parcours', 'j12_actions_pages (page /voice)'),
    'voice.api_voice_info': ('parcours', 'j12_actions_pages (page /voice)'),
    'voice.voice_audio': ('exclu', 'fichier produit servi : rien à servir sans génération'),
    'webauthn.api_security': ('exclu', 'sécurité du compte (2FA) : lecture liée aux passkeys'),
    'webauthn.security_register_begin': ('exclu', '2FA par passkey : nécessite un matériel physique (clé FIDO2)'),
    'webauthn.security_register_finish': ('exclu', '2FA par passkey : nécessite un matériel physique (clé FIDO2)'),
    'webauthn.security_remove': ('exclu', '2FA par passkey : nécessite un matériel physique (clé FIDO2)'),
    'webauthn.security_toggle': ('exclu', '2FA par passkey : nécessite un matériel physique (clé FIDO2)'),
    'webauthn.security_verify_login': ('exclu', '2FA par passkey : nécessite un matériel physique (clé FIDO2)'),
}
